on:
  workflow_dispatch:
    inputs:
      hook_payload:
        description: "The payload received from the hook"
        required: true
        type: string
permissions:
  contents: write
  
jobs:
  scaffold:
    runs-on: ubuntu-latest
    steps:
      - name: Scaffold
        uses: platform-d09/gh-action-newrepo@v1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo_name: ${{ fromJson(inputs.hook_payload).name }}
          cookiecutter_template: ${{ fromJson(inputs.hook_payload).template_url }}
          org_name: ${{ fromJson(inputs.hook_payload).gh_org }}
          user_inputs: ${{ toJson(fromJson(inputs.hook_payload).user_inputs) }}